### ISSUE TITLE
Can't copy files across internal and external storages

### ISSUE THREAD

**Issue by eduardopatricio** [afollestad/cabinet-issue-tracker#318] opened 2015-11-03 09:28 UTC
For example, after selecting a file to be copied from the internal storage, the hamburger menu becomes unavailable and I can't navigate to external storage.

**Comment by afollestad** [comment] 2015-11-03 13:44
Duplicate of countless closed issues which were also duplicates.

**Closed by afollestad** 2015-11-03 13:44 UTC
