### ISSUE TITLE
When doing a quick flick to scroll down, the floating action button temporarily hides itself momentarily

### ISSUE THREAD

**Issue by Keavon** [afollestad/cabinet-issue-tracker#137] opened 2015-04-03 04:05 UTC
When scrolling to the bottom quickly by flicking through a short list, floating action button hides itself momentarily before quickly reappearing when it reaches the bottom of the list. This is useful when you are manually dragging to the bottom of the list, but looks bad/distracting when it animates down and then reappears 100 milliseconds later. It should instead predict if the scroll will reach the bottom and if it will, don't hide the floating action button.

**Comment by afollestad** [comment] 2015-04-03 04:06
That's not a bug, the FAB hides itself when you scroll down. When you scroll back up, or reach the space at the bottom of the list, it shows itself again.

**Comment by Keavon** [comment] 2015-04-03 04:09
This was intended as an enhancement, not a bug. If the scrolling action is going to reach the bottom with that scroll, the floating action button should not disappear and then immediately reappear once it hits the bottom because it acts as a distracting and unnecessary animation. When doing slow scrolling, this is useful for the button to hide itself, and when it reaches the bottom, it is useful for the button to reappear, but when you move directly to the bottom, it should not do this.

**Comment by afollestad** [comment] 2015-04-03 04:10
Hmm, good point. I'm not sure if there's really any efficient or good way to do this, but I'll see what I can do.

**Comment by plusCubed** [comment] 2015-04-03 04:11
I'm not sure there's a way to predict fling position, but I suppose we can keep the FAB on screen while flinging, and hide if necessary when fling comes to stop. If the user keeps their finger on the screen while scrolling, hide/show as necessary.

**Comment by Keavon** [comment] 2015-04-03 04:23
I suppose it could be a rough prediction. Determine the velocity of the fling in the first few milliseconds and compare it to the size of the list. If it's a small list and it seems to have approximately sufficient velocity, it should keep the button open. The prediction can be adapted during the scroll if it appears it won't be reaching the bottom, the button can be hidden. If it does reach the bottom after it was hidden by an inaccurate prediction, it will have been going slow enough that the time since it dropped won't be too distracting so the act of popping up is fine. Basically just do a little bit of experimentation to get something that works well enough.

**Comment by afollestad** [comment] 2015-04-03 04:25
That's just a lot of unnecessary calculation for a mobile app.

I think it would make more sense to never hide the FAB at all if there's only a certain amount of available space for scrolling.

**Comment by Keavon** [comment] 2015-04-03 04:27
Actually, that's a good point. If I was scrolling and needed to see something, I would just scroll up a little more so the button doesn't block it as long as I had enough screen space.

**Comment by afollestad** [comment] 2015-04-03 04:28
Well I mean it would still hide with longer lists, but with short lists where you reach the end almost immediately after scrolling (e.g. if the Y coordinate of the space at the bottom is near the last visible list item) then disable hiding.

**Comment by Keavon** [comment] 2015-04-03 04:29
Yep, that seems quite logical.

**Comment by afollestad** [comment] 2015-04-08 00:03
This doesn't seem like a serious enough issue so I'm gonna close it to keep this repo minimal.

**Closed by afollestad** 2015-04-08 00:03 UTC
Labels: enhancement, low priority
