### ISSUE TITLE
unable to delete files/folders from external SD card

### ISSUE THREAD

**Issue by goonta** [afollestad/cabinet-issue-tracker#223] opened 2015-05-22 14:56 UTC
I'm having what appears to be the same issue as one reported back in February (Weird folder deletion issue #104) but was apparently unable to be verified and thus was closed. I can delete from my internal memory but when attempting to delete from my external SD card the app fails. When attempting to delete folders the app just hangs on "deleting..." but when attempting to delete files I get "Failed to delete this file: unknown error". I've tried cycling power to no avail. Device is AT&T's Galaxy Note 4 (N10A) on stock ROM Build LRX22C.N910AUCU1COC4, Android 5.0.1

**Comment by afollestad** [comment] 2015-05-22 16:02
Duplicate of many closed issues, and related to an open issue.

**Closed by afollestad** 2015-05-22 16:02 UTC
