### ISSUE TITLE
Open/view .apk as a folder

### ISSUE THREAD

**Issue by codeversed** [afollestad/cabinet-issue-tracker#284] opened 2015-08-17 13:21 UTC
Would love to be able to browse an apk as a folder. This would be a nice enhancement. Even if you added an open as -> folder, that would suffice.

**Comment by afollestad** [comment] 2015-08-18 01:03
Duplicate of https://github.com/afollestad/cabinet-issue-tracker/issues/276

**Comment by codeversed** [comment] 2015-08-20 14:12
"You can rename it to a ZIP; installation is a primary action for that." 

True, but kind of a pain. Adding the open as option would allow the primary action handle installation like it does now but gives you the extra ability to browse without renaming (most likely would copy, then rename in such a situation).

**Comment by AndreRoss** [comment] 2015-08-27 06:42
@afollestad How do you think this should be realized from ux perspective? I would suggest an additional entry "View" or "Browse" in the file menu for apk files.

**Closed** 2015-08-28 06:07 UTC
Labels: enhancement, low priority
