### ISSUE TITLE
Devices with physical menu button – wrong overflow dialog theme

### ISSUE THREAD

**Issue by Keavon** [afollestad/cabinet-issue-tracker#139] opened 2015-04-03 04:50 UTC
Using the phone's hardware menu key with the actions popup at the bottom works fine, but clicking Grid Size item makes its option appear behind the menu with white-on-white text. The menu is also too big, making it seem like there needs to be text other than the numbers in that space.

![Screenshot](https://cloud.githubusercontent.com/assets/4388688/6978181/1f0611fa-d982-11e4-8378-59d81db30c3e.png)

Also, the checked box appears too dark in the actions popup menu while the unchecked box is correctly colored.

**Comment by afollestad** [comment] 2015-04-03 05:16
This is actually an issue with some Samsung devices and other devices with a physical menu button (which is not what Google intended for the latest versions of Android).

It should look like this:

![screenshot_2015-04-03-00-14-53](https://cloud.githubusercontent.com/assets/1820165/6978354/920dac3a-d996-11e4-804b-2df80535987a.png)

There's some issues with how those devices that have physical menu buttons theme the dialogs that are used to replace the PopupMenu sub menu.

**Comment by afollestad** [comment] 2015-04-03 05:17
There was actually an issue for this on the old repository when Cabinet was open source but I never re-added it. I'll have to look into it again.

**Comment by afollestad** [comment] 2015-04-03 05:20
There was actually an issue for this on the old repository when Cabinet was open source but I never re-added it. I'll have to look into it again.

It isn't blank, the font is just white because it expects the dialog background to be dark (since the main app theme is light content with a dark, or blue in this case, toolbar).

**Comment by Keavon** [comment] 2015-04-03 05:20
It looks like your screenshot when I use the three dots menu. It would be ideal—if it's possible—to hook the physical menu button press event and make that menu manually appear near the bottom of the screen rather than using the variation that's done automatically by the OS.

**Comment by afollestad** [comment] 2015-04-03 05:20
Oddly enough, that is what's done on some devices. But others refuse to do it correctly for some reason.

**Comment by afollestad** [comment] 2015-04-03 05:21
That's what's done with the top level menus, but once you get into sub menus, it's all handled by the OS and there's no way to hook into those events. The only way is to find the right theming attributes that are used to theme the dialog that's shown there, but I've never really been successful.

There's actually a bug logged somewhere on the Android Open Source Project I believe.

**Comment by Keavon** [comment] 2015-04-03 05:23
If it helps to know my system, I'm using a Galaxy Note II running Android 4.4.4 with CyanogenMod 11.

**Comment by afollestad** [comment] 2015-04-03 05:24
I had a feeling it was a Samsung device.

But yeah, I'll see if I can find the source of the dialog theming there. But otherwise Samsung users might have to wait for a fix from Google or Samsung. Although it's very possible it was already fixed on Lollipop (5.0, 5.0.1, 5.0.2, or 5.1).

**Comment by afollestad** [comment] 2015-04-09 17:27
Even if I use an emulator to run Cabinet on 4.2 and 4.4, this issue does not come up. It's specific to Samsung devices unfortunately, and I don't think there's an easy fix. You should upgrade to 5.0 ASAP.

**Closed by afollestad** 2015-04-09 17:27 UTC
Labels: bug, low priority

**Comment by plusCubed** [comment] 2015-04-10 04:16
I can reproduce this with the Genymotion 4.x emulators (I don't think it has to do with Samsung since he's running Cyanogenmod - based on AOSP). Either way, I've changed it so pressing the menu button just opens the overflow menu now (avoiding the issue rather than fixing it - this might be a bit of an annoyance to those used to using the menu on the bottom).
